# Generated by Django 5.2.9 on 2025-12-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, help_text="İkon kodlarını <a href='https://fontawesome.com/search?o=r&m=free' target='_blank'>buradan</a> bulup kopyalayın. Örn: <b>fa-solid fa-laptop</b>", max_length=50, null=True, verbose_name='İkon Sınıfı (FontAwesome)'),
        ),
    ]
